package erd

import (
	"encoding/json"
	"fmt"
)

// The generated-facts artifact: FactsJSON turns an introspected Schema into the
// docs/src/generated/schema.json document the docs site renders storage tables
// from. Same source as the ERD (the migrated catalog), same drift discipline
// (a committed artifact plus a test that re-introspects), different consumer:
// the ERD carries the relational skeleton, the facts carry the column detail a
// page's storage table used to hand-write.

type factsColumn struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Nullable bool   `json:"nullable"`
	Default  string `json:"default,omitempty"`
	PK       bool   `json:"pk,omitempty"`
	FK       bool   `json:"fk,omitempty"`
	FKTarget string `json:"fk_target,omitempty"`
}

type factsCheck struct {
	Name string `json:"name"`
	Expr string `json:"expr"`
}

type factsUnique struct {
	Name       string `json:"name"`
	Definition string `json:"definition"`
}

type factsTable struct {
	Columns []factsColumn `json:"columns"`
	Checks  []factsCheck  `json:"checks,omitempty"`
	Uniques []factsUnique `json:"uniques,omitempty"`
}

type factsDoc struct {
	Comment    string                           `json:"//"`
	Subsystems map[string]map[string]factsTable `json:"subsystems"`
}

// FactsJSON renders the schema facts document, keyed by subsystem then table
// (the same cluster map as the ERD; an unmapped table lands under
// "unclustered" so it cannot vanish). Deterministic: maps marshal key-sorted,
// columns keep catalog ordinal order, checks and uniques arrive name-ordered
// from introspection. The trailing newline makes the committed file
// POSIX-clean.
func FactsJSON(s Schema, clusters []Cluster) ([]byte, error) {
	loc := map[string]string{}
	for _, c := range clusters {
		for _, t := range c.Tables {
			loc[t] = c.Name
		}
	}

	doc := factsDoc{
		Comment:    "generated by make gen (cmd/erdgen); do not edit",
		Subsystems: map[string]map[string]factsTable{},
	}
	for _, t := range s.Tables {
		sub, ok := loc[t.Name]
		if !ok {
			sub = unclustered
		}
		fkTarget := map[string]string{}
		for _, fk := range t.FKs {
			fkTarget[fk.Column] = fk.RefTable + "." + fk.RefColumn
		}
		ft := factsTable{Columns: make([]factsColumn, 0, len(t.Columns))}
		for _, c := range t.Columns {
			ft.Columns = append(ft.Columns, factsColumn{
				Name: c.Name, Type: c.Type, Nullable: c.Nullable, Default: c.Default,
				PK: c.PK, FK: c.FK, FKTarget: fkTarget[c.Name],
			})
		}
		for _, ck := range t.Checks {
			ft.Checks = append(ft.Checks, factsCheck{Name: ck.Name, Expr: ck.Expr})
		}
		for _, u := range t.Uniques {
			ft.Uniques = append(ft.Uniques, factsUnique{Name: u.Name, Definition: u.Definition})
		}
		if doc.Subsystems[sub] == nil {
			doc.Subsystems[sub] = map[string]factsTable{}
		}
		doc.Subsystems[sub][t.Name] = ft
	}

	out, err := json.MarshalIndent(doc, "", " ")
	if err != nil {
		return nil, fmt.Errorf("erd: marshal facts: %w", err)
	}
	return append(out, '\n'), nil
}
