// Command erdgen renders the platform entity-relationship diagram from the live
// schema, the storage arm of the generation pipeline. It applies the embedded
// migrations to a throwaway Postgres (a testcontainer, or $DATABASE_URL if set),
// introspects the catalog, and rewrites the generated D2 region of the data-model
// docs page. Because the source is the migrated schema itself, the diagram can
// never drift from the tables: a schema change that forgets `make gen` shows up
// in the ERD drift test. The committed D2 is reviewed like any generated code and
// rendered to SVG by `pnpm diagrams`; do not hand-edit the region.
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/testcontainers/testcontainers-go"
	tcpostgres "github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/wait"

	"github.com/hyperscaleav/omniglass/internal/erd"
	"github.com/hyperscaleav/omniglass/internal/migrate"
)

const dst = "docs/src/content/docs/architecture/data-model.md"

const (
	beginMarker = "<!-- erd:begin (generated by make gen; edit cmd/erdgen, not here) -->"
	endMarker   = "<!-- erd:end -->"
)

func main() {
	ctx := context.Background()

	dsn, cleanup, err := acquireDSN(ctx)
	if err != nil {
		log.Fatalf("erdgen: acquire postgres: %v", err)
	}
	defer cleanup()

	if err := migrate.Run(dsn); err != nil {
		log.Fatalf("erdgen: migrate: %v", err)
	}

	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		log.Fatalf("erdgen: connect: %v", err)
	}
	defer conn.Close(ctx)

	schema, err := erd.Introspect(ctx, conn)
	if err != nil {
		log.Fatalf("erdgen: introspect: %v", err)
	}
	d2, err := erd.Render(schema, erd.Subsystems)
	if err != nil {
		log.Fatalf("erdgen: render: %v", err)
	}
	if err := rewriteRegion(dst, d2); err != nil {
		log.Fatalf("erdgen: %v", err)
	}
	log.Printf("wrote ERD region to %s (%d tables)", dst, len(schema.Tables))
}

// acquireDSN returns a DSN to a migratable Postgres and a cleanup func. It uses
// $DATABASE_URL when set (a CI service database), otherwise starts an ephemeral
// postgres:18 testcontainer, the same capability the integration tests use.
func acquireDSN(ctx context.Context) (string, func(), error) {
	if env := os.Getenv("DATABASE_URL"); env != "" {
		return env, func() {}, nil
	}
	c, err := tcpostgres.Run(ctx, "postgres:18",
		tcpostgres.WithDatabase("omniglass"),
		tcpostgres.WithUsername("omniglass"),
		tcpostgres.WithPassword("omniglass"),
		testcontainers.WithWaitStrategy(
			wait.ForLog("database system is ready to accept connections").
				WithOccurrence(2).WithStartupTimeout(60*time.Second)),
	)
	if err != nil {
		return "", nil, err
	}
	dsn, err := c.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		_ = testcontainers.TerminateContainer(c)
		return "", nil, err
	}
	return dsn, func() { _ = testcontainers.TerminateContainer(c) }, nil
}

// rewriteRegion replaces the D2 between the begin and end markers in path with a
// fenced d2 block, preserving the markers and all prose around them. The markers
// must already exist; a missing marker is an error, not a silent full-file write.
func rewriteRegion(path, d2 string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	content := string(raw)
	bi := strings.Index(content, beginMarker)
	ei := strings.Index(content, endMarker)
	if bi < 0 || ei < 0 || ei < bi {
		return fmt.Errorf("%s: missing or malformed erd:begin/erd:end markers", path)
	}
	before := content[:bi+len(beginMarker)]
	after := content[ei:]
	block := "\n\n```d2\n" + d2 + "```\n\n"
	return os.WriteFile(path, []byte(before+block+after), 0o644)
}
