import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema.gen";

// Typed client over the Huma API. Two auth paths, both accepted by the server: a
// human signs in with a password and gets an httpOnly session cookie (sent
// automatically because every request includes credentials), and a service or
// operator can instead paste a bearer token, which is stored and attached as an
// Authorization header. The base is origin-absolute so it resolves in every fetch
// implementation (the browser, and undici in tests). Types come from
// schema.gen.ts (regenerated by `make gen`), so the client cannot drift.
const TOKEN_KEY = "og-token";

export function getToken(): string {
  return localStorage.getItem(TOKEN_KEY) ?? "";
}
export function setToken(token: string): void {
  localStorage.setItem(TOKEN_KEY, token);
}
export function clearToken(): void {
  localStorage.removeItem(TOKEN_KEY);
}

const origin = typeof globalThis.location !== "undefined" ? globalThis.location.origin : "";
export const api = createClient<paths>({
  baseUrl: `${origin}/api/v1`,
  // The console is same-origin (served by the binary; vite proxies /api in dev),
  // so the session cookie rides automatically; include is set for robustness.
  credentials: "include",
  // Defer to the current global fetch on every call so tests can stub it.
  fetch: (input) => globalThis.fetch(input),
});

// Attach a stored bearer token (the optional token path) on top of the session
// cookie; the server accepts either.
const authMiddleware: Middleware = {
  async onRequest({ request }) {
    const token = getToken();
    if (token) request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
};
api.use(authMiddleware);
