import createClient from "openapi-fetch";
import type { paths } from "./schema.gen";

// Typed client over the Huma API. The console authenticates with an httpOnly
// session cookie set by POST /auth/login; the SPA never reads or stores a token.
// Every request includes credentials so the cookie rides along (same-origin,
// served by the Go binary; under `npm run dev` Vite proxies /api to the server).
// The base is origin-absolute so it resolves in every fetch implementation (the
// browser, and undici in tests). Types come from schema.gen.ts (regenerated by
// `make gen`), so the client cannot drift.
const origin = typeof globalThis.location !== "undefined" ? globalThis.location.origin : "";
export const api = createClient<paths>({
  baseUrl: `${origin}/api/v1`,
  // credentials is baked into the Request openapi-fetch builds, so the session
  // cookie rides on every call.
  credentials: "include",
  // Defer to the current global fetch on every call (so tests can stub it); the
  // Request already carries credentials and headers.
  fetch: (input) => globalThis.fetch(input),
});
