/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with a username and password
         * @description Verifies a human's password and sets an httpOnly session cookie. Public; a bad credential is a flat 401, and a correct password against a disabled account is a distinct 403 so the screen can explain it.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the current session
         * @description Revokes the session token and clears the cookie. Public.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated principal, its permissions, and grants
         * @description Returns the caller's principal, flattened permissions (a UI hint and the fast-reject set), and grants. Requires authentication.
         */
        get: operations["get-auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your own profile
         * @description Updates the caller's own display name (email is administrator-set). Requires authentication; self-scoped (edits only your own principal).
         */
        patch: operations["update-auth-me"];
        trace?: never;
    };
    "/auth/me:changePassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Verifies the current password and sets a new one. Requires authentication; self-scoped.
         */
        post: operations["change-auth-me-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me:stopImpersonation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop the current impersonation session
         * @description Revokes the impersonation session presented by the request token, ending the view-as / act-as. Requires an impersonation token.
         */
        post: operations["stop-impersonation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether the system has an owner yet
         * @description Public: reports whether any owner has been bootstrapped, so the login screen can hide the bootstrap hint.
         */
        get: operations["get-auth-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List components in scope
         * @description Lists the components the caller may read, each filtered to its scope subtree. Gated by component:read.
         */
        get: operations["list-components"];
        put?: never;
        /**
         * Create a component
         * @description Creates a component, optionally under a parent (a root needs an all-scoped grant), bound to a system and a location. Gated by component:create.
         */
        post: operations["create-component"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a component
         * @description Fetches a component by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by component:read.
         */
        get: operations["get-component"];
        put?: never;
        post?: never;
        /**
         * Delete a component
         * @description Deletes a component, refused while it still has child components. Gated by component:delete; read and delete scopes drive the 404 versus 403 split.
         */
        delete: operations["delete-component"];
        options?: never;
        head?: never;
        /**
         * Update a component
         * @description Patches a component's display_name or component_type. Gated by component:update; read and update scopes drive the 404 versus 403 split.
         */
        patch: operations["update-component"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and database-reachability probe
         * @description Reports process health and the database leg, pinged through the Storage Gateway.
         */
        get: operations["get-healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List location types
         * @description Lists the location_type registry (the shape-definers a location is classified by), ordered by rank. Populates the type picker on the location form. Gated by location:read.
         */
        get: operations["list-location-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locations in scope
         * @description Lists the locations the caller may read, each filtered to its scope subtree. Gated by location:read.
         */
        get: operations["list-locations"];
        put?: never;
        /**
         * Create a location
         * @description Creates a location, optionally under a parent (a root needs an all-scoped grant). Gated by location:create.
         */
        post: operations["create-location"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a location
         * @description Fetches a location by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by location:read.
         */
        get: operations["get-location"];
        put?: never;
        post?: never;
        /**
         * Delete a location
         * @description Deletes a location, refused while it still has child locations. Gated by location:delete; read and delete scopes drive the 404 versus 403 split.
         */
        delete: operations["delete-location"];
        options?: never;
        head?: never;
        /**
         * Update a location
         * @description Patches a location's display_name or location_type. Gated by location:update; the read and update scopes drive the 404 versus 403 split.
         */
        patch: operations["update-location"];
        trace?: never;
    };
    "/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List principals
         * @description Lists all principals (humans and service accounts) with their grants. Gated by principal:read, which confers access only at all-scope.
         */
        get: operations["list-principals"];
        put?: never;
        /**
         * Create a human principal
         * @description Creates a human principal with an optional initial password. Gated by principal:create (all-scope). The new principal holds no grants; assign roles separately.
         */
        post: operations["create-principal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/principals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a principal
         * @description Fetches one principal by id with its profile and grants. Gated by principal:read (all-scope).
         */
        get: operations["get-principal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a principal
         * @description Updates a human principal's display name, email, and username. Gated by principal:update (all-scope). Renaming is safe: nothing keys on the username.
         */
        patch: operations["update-principal"];
        trace?: never;
    };
    "/principals/{id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant a role to a principal
         * @description Assigns a role at a scope to a principal. Gated by principal_grant:create (all-scope). Refused (403) when the granted role's capabilities exceed the granter's own (no promoting anyone, including yourself, to a higher tier such as owner). A duplicate is 409, an unknown role or bad scope 422.
         */
        post: operations["create-grant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/principals/{id}/grants/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a grant
         * @description Removes one grant from a principal. Gated by principal_grant:delete (all-scope). The last owner grant cannot be revoked.
         */
        delete: operations["revoke-grant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/principals/{id}:disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable a principal
         * @description Soft-disables a principal so it can no longer authenticate; its audit trail is kept. Gated by principal:update (all-scope). The last active owner cannot be disabled.
         */
        post: operations["disable-principal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/principals/{id}:enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable a principal
         * @description Re-enables a disabled principal, restoring its ability to authenticate. Gated by principal:update (all-scope).
         */
        post: operations["enable-principal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/principals/{id}:impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Impersonate a principal (view-as or act-as)
         * @description Mints a bounded, revocable token to view as (read-only) or act as (full) the target. Gated by principal:impersonate (all-scope). Refused on self, on an owner target (owners are un-impersonatable by anyone), when it would grant a capability the caller lacks (the escalation guard), or from within an existing impersonation.
         */
        post: operations["impersonate-principal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Lists the roles. Gated by the role:read capability.
         */
        get: operations["list-roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List systems in scope
         * @description Lists the systems the caller may read, each filtered to its scope subtree. Gated by system:read.
         */
        get: operations["list-systems"];
        put?: never;
        /**
         * Create a system
         * @description Creates a system, optionally under a parent (a root needs an all-scoped grant) and at a location. Gated by system:create.
         */
        post: operations["create-system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a system
         * @description Fetches a system by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by system:read.
         */
        get: operations["get-system"];
        put?: never;
        post?: never;
        /**
         * Delete a system
         * @description Deletes a system, refused while it still has child systems. Gated by system:delete; read and delete scopes drive the 404 versus 403 split.
         */
        delete: operations["delete-system"];
        options?: never;
        head?: never;
        /**
         * Update a system
         * @description Patches a system's display_name or system_type. Gated by system:update; read and update scopes drive the 404 versus 403 split.
         */
        patch: operations["update-system"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthStatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/AuthStatusOutputBody.json
             */
            readonly $schema?: string;
            bootstrapped: boolean;
        };
        ChangePasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ChangePasswordInputBody.json
             */
            readonly $schema?: string;
            /** @description Your current password */
            current_password: string;
            /** @description The new password (at least 8 characters) */
            new_password: string;
        };
        ComponentBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ComponentBody.json
             */
            readonly $schema?: string;
            /** @description The scope-aware actions the caller may perform on this row (create a child, update, delete); a UI hint, the server still enforces. */
            actions?: string[] | null;
            component_type: string;
            display_name?: string;
            id: string;
            location_id?: string;
            name: string;
            parent_id?: string;
            system_id?: string;
        };
        CreateComponentInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateComponentInputBody.json
             */
            readonly $schema?: string;
            /** @description A component_type id */
            component_type: string;
            display_name?: string;
            /** @description Location name this component is placed at */
            location?: string;
            /** @description Globally unique name (the address) */
            name: string;
            /** @description Parent component name; omit for a root component */
            parent?: string;
            /** @description Primary system name this component belongs to */
            system?: string;
        };
        CreateGrantInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateGrantInputBody.json
             */
            readonly $schema?: string;
            /** @description A role id (viewer, operator, admin, owner, or a custom role) */
            role: string;
            /** @description The scope root id; omit for the all scope */
            scope_id?: string;
            /**
             * @description The scope kind; 'all' confers the whole estate
             * @enum {string}
             */
            scope_kind: "all" | "location" | "system" | "component" | "group";
            /**
             * @description How the scope root matches the tree: subtree (root + descendants, the default), subtree_excl_root (descendants only for update/delete, root kept for read/create), or self (the root row only). Moot for the all scope.
             * @enum {string}
             */
            scope_op?: "subtree" | "subtree_excl_root" | "self";
        };
        CreateLocationInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateLocationInputBody.json
             */
            readonly $schema?: string;
            display_name?: string;
            /** @description A location_type id (campus, building, ...) */
            location_type: string;
            /** @description Globally unique name (the address) */
            name: string;
            /** @description Parent location name; omit for a root location */
            parent?: string;
        };
        CreatePrincipalInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreatePrincipalInputBody.json
             */
            readonly $schema?: string;
            display_name?: string;
            email?: string;
            /** @description Optional initial password; the user changes it after signing in */
            password?: string;
            /** @description Unique sign-in name */
            username: string;
        };
        CreateSystemInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateSystemInputBody.json
             */
            readonly $schema?: string;
            display_name?: string;
            /** @description Location name this system is placed at */
            location?: string;
            /** @description Globally unique name (the address) */
            name: string;
            /** @description Parent system name; omit for a root system */
            parent?: string;
            /** @description A system_type id */
            system_type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GrantBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/GrantBody.json
             */
            readonly $schema?: string;
            id?: string;
            role: string;
            scope_id?: string;
            scope_kind: string;
            /**
             * @description How the scope root matches the tree: subtree (root + descendants), subtree_excl_root (descendants only for update/delete, root kept for read/create), or self (the root row only). Empty means subtree. Moot for the all scope.
             * @enum {string}
             */
            scope_op?: "subtree" | "subtree_excl_root" | "self";
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @description Database leg via the Storage Gateway: ok or down */
            db: string;
            /** @description Overall health: ok when all legs pass, degraded otherwise */
            status: string;
        };
        HumanBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/HumanBody.json
             */
            readonly $schema?: string;
            display_name?: string;
            email?: string;
            username: string;
        };
        ImpersonateInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ImpersonateInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Session lifetime in minutes (default 30, max 1440)
             */
            duration_minutes?: number;
            /**
             * @description view_as is read-only; act_as is full, with mutations attributed to both the real actor and the impersonated principal
             * @enum {string}
             */
            mode: "view_as" | "act_as";
        };
        ImpersonateOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ImpersonateOutputBody.json
             */
            readonly $schema?: string;
            expires_at: string;
            mode: string;
            target_id: string;
            /** @description The bearer token to send while impersonating; shown once */
            token: string;
        };
        ListComponentsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ListComponentsOutputBody.json
             */
            readonly $schema?: string;
            components: components["schemas"]["ComponentBody"][] | null;
        };
        ListLocationTypesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ListLocationTypesOutputBody.json
             */
            readonly $schema?: string;
            location_types: components["schemas"]["LocationTypeBody"][] | null;
        };
        ListLocationsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ListLocationsOutputBody.json
             */
            readonly $schema?: string;
            locations: components["schemas"]["LocationBody"][] | null;
        };
        ListPrincipalsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ListPrincipalsOutputBody.json
             */
            readonly $schema?: string;
            principals: components["schemas"]["PrincipalBody"][] | null;
        };
        ListSystemsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ListSystemsOutputBody.json
             */
            readonly $schema?: string;
            systems: components["schemas"]["SystemBody"][] | null;
        };
        LocationBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LocationBody.json
             */
            readonly $schema?: string;
            /** @description The scope-aware actions the caller may perform on this row (create a child, update, delete); a UI hint, the server still enforces. */
            actions?: string[] | null;
            display_name?: string;
            id: string;
            location_type: string;
            name: string;
            parent_id?: string;
        };
        LocationTypeBody: {
            display_name: string;
            id: string;
            official: boolean;
            /** Format: int64 */
            rank: number;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            password: string;
            username: string;
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            grants: components["schemas"]["GrantBody"][] | null;
            human?: components["schemas"]["HumanBody"];
            permissions: string[] | null;
            principal: components["schemas"]["PrincipalStruct"];
            service?: components["schemas"]["SvcBody"];
        };
        PrincipalBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/PrincipalBody.json
             */
            readonly $schema?: string;
            active: boolean;
            grants: components["schemas"]["GrantBody"][] | null;
            human?: components["schemas"]["HumanBody"];
            id: string;
            kind: string;
            service?: components["schemas"]["SvcBody"];
        };
        PrincipalStruct: {
            id: string;
            kind: string;
        };
        RoleBody: {
            id: string;
            inherits: string[] | null;
            official: boolean;
            permissions: string[] | null;
        };
        RolesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/RolesOutputBody.json
             */
            readonly $schema?: string;
            roles: components["schemas"]["RoleBody"][] | null;
        };
        SvcBody: {
            label: string;
        };
        SystemBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SystemBody.json
             */
            readonly $schema?: string;
            /** @description The scope-aware actions the caller may perform on this row (create a child, update, delete); a UI hint, the server still enforces. */
            actions?: string[] | null;
            display_name?: string;
            id: string;
            location_id?: string;
            name: string;
            parent_id?: string;
            system_type: string;
        };
        UpdateComponentInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateComponentInputBody.json
             */
            readonly $schema?: string;
            component_type?: string;
            display_name?: string;
        };
        UpdateLocationInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateLocationInputBody.json
             */
            readonly $schema?: string;
            display_name?: string;
            location_type?: string;
        };
        UpdateMeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateMeInputBody.json
             */
            readonly $schema?: string;
            /** @description Your display name; empty clears it */
            display_name?: string;
        };
        UpdatePrincipalInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdatePrincipalInputBody.json
             */
            readonly $schema?: string;
            /** @description Display name; empty clears it */
            display_name?: string;
            /** @description Email; empty clears it */
            email?: string;
            /** @description Sign-in name; renaming is safe */
            username?: string;
        };
        UpdateSystemInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateSystemInputBody.json
             */
            readonly $schema?: string;
            display_name?: string;
            system_type?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "change-auth-me-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stop-impersonation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-auth-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListComponentsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-component": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComponentInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The component's unique name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The component's unique name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateComponentInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-location-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLocationTypesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLocationsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-location": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The location's unique name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-location": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The location's unique name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-location": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-principals": {
        parameters: {
            query?: {
                /** @description Optionally filter by principal kind */
                kind?: "human" | "service";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPrincipalsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-principal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrincipalInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-principal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal's id (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-principal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal's id (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrincipalInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-grant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal's id (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrantInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "revoke-grant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal's id (uuid) */
                id: string;
                /** @description The grant's id (uuid) */
                grantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "disable-principal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal's id (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "enable-principal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal's id (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "impersonate-principal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The principal to impersonate (uuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpersonateInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpersonateOutputBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSystemsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSystemInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-system": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The system's unique name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-system": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The system's unique name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-system": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSystemInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
