apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omniglass.fullname" . }}-dsn
  labels:
    {{- include "omniglass.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ include "omniglass.dsn" . | quote }}
