// Vendors the console's two typefaces into the repo, and generates the stylesheet
// that declares them (#775).
//
// The console used to link fonts.googleapis.com, so rendering correctly depended
// on reaching a third party at runtime: wrong for an estate on a closed campus or
// AV network, and the direct cause of a docs capture writing a fallback-font PNG
// that the zero-tolerance freshness gate reported as UI drift.
//
// This script is the generator for src/fonts.css and public/fonts/*.woff2. Neither
// is hand-edited, and neither is regenerated by `make gen`: the source is a network
// fetch, so pinning the bytes in git is the point. Re-run it deliberately, when a
// weight, a script, or a family changes:
//
//	node web/scripts/vendor-fonts.mjs
//
// It fetches the SAME css2 request the console used to link, with a browser user
// agent so Google serves woff2 with its per-script unicode-range split, then
// rewrites each src to the local copy. Vendoring Google's own files rather than a
// fresh build from the upstream repos is deliberate: they are the exact binaries
// the console rendered with before, so the committed screenshots stay valid and any
// raster change would be a real finding rather than a build-difference artifact.
//
// Licensing: both families are OFL 1.1, which permits redistribution and requires
// the license to travel with the fonts. The two OFL.txt files land beside the
// woff2 in public/fonts/, so they ship inside the binary and are served next to
// the faces they cover. Attribution is in the repo NOTICE.
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

// The exact request web/index.html used to carry: IBM Plex Sans 400/500/600/700
// plus italic 400, JetBrains Mono 400/500/600/700.
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400" +
  "&family=JetBrains+Mono:wght@400;500;600;700&display=swap";

// A modern desktop UA, because the css2 endpoint serves woff2 (and the
// unicode-range split) only to clients it believes support them.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// OFL 1.1 text from each family's own repository, pinned to a tag so a re-run
// fetches the same bytes.
const LICENSES = {
  "ibm-plex-sans-OFL.txt":
    "https://raw.githubusercontent.com/IBM/plex/%40ibm%2Fplex-sans%401.1.0/packages/plex-sans/LICENSE.txt",
  "jetbrains-mono-OFL.txt":
    "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/v2.304/OFL.txt",
};

const FONT_DIR = new URL("../public/fonts/", import.meta.url);
const CSS_OUT = new URL("../src/fonts.css", import.meta.url);

const get = async (url) => {
  const res = await fetch(url, { headers: { "user-agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res;
};

await mkdir(FONT_DIR, { recursive: true });

const css = await (await get(CSS_URL)).text();

// Google emits one `/* <script> */` comment per @font-face block, which is the
// only place the subset is named; the unicode-range descriptor is what keeps a
// browser downloading the latin file alone for a latin page.
const faces = [];
for (const chunk of css.split("/*").slice(1)) {
  const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
  const family = /font-family:\s*'([^']+)'/.exec(chunk)?.[1];
  const style = /font-style:\s*(\w+)/.exec(chunk)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(chunk)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(chunk)?.[1];
  const url = /url\(([^)]+)\)\s*format\('woff2'\)/.exec(chunk)?.[1];
  if (!url) continue;
  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const file = `${slug}-${subset}-${weight}${style === "italic" ? "-italic" : ""}.woff2`;
  faces.push({ subset, family, style, weight, range, url, file, slug });
}
if (faces.length === 0) throw new Error("no @font-face blocks parsed from the css2 response");

let total = 0;
for (const face of faces) {
  const buf = Buffer.from(await (await get(face.url)).arrayBuffer());
  await writeFile(new URL(face.file, FONT_DIR), buf);
  face.bytes = buf.length;
  face.sha = createHash("sha256").update(buf).digest("hex").slice(0, 12);
  total += buf.length;
}

for (const [file, url] of Object.entries(LICENSES)) {
  // Verbatim except for line endings: IBM serves theirs CRLF and this repo is LF
  // (.editorconfig). The text is untouched.
  const text = (await (await get(url)).text()).replace(/\r\n/g, "\n");
  await writeFile(new URL(file, FONT_DIR), text);
}

// Stable order so a re-run that changes nothing produces no diff.
const order = (a, b) =>
  a.family.localeCompare(b.family) ||
  a.style.localeCompare(b.style) ||
  Number(a.weight) - Number(b.weight) ||
  a.subset.localeCompare(b.subset);

const header = `/* GENERATED by web/scripts/vendor-fonts.mjs. Do not edit.
 *
 * The console's typefaces, served from this origin (public/fonts/, copied verbatim
 * into the Vite output that internal/webui/spa_embed.go compiles into the binary),
 * so the console renders correctly with no network beyond the one that served it.
 *
 * font-display: block, not swap. The file is same-origin and embedded in the same
 * binary as the document, so the block period costs nothing measurable, and block
 * is the only value that cannot paint fallback metrics: swap paints them by
 * definition and optional can keep them for the life of the page. A capture that
 * renders one shot in the fallback face is what #775 was.
 *
 * unicode-range keeps the split Google serves: a latin page fetches the latin file
 * only, and a codepoint no block covers falls through to the next family in
 * --og-font-ui / --og-font-data (app.css), which is what already happened for any
 * script these families do not carry.
 *
 * ${faces.length} files, ${total.toLocaleString("en-US")} bytes.
 */
`;

const blocks = faces.sort(order).map(
  (f) => `/* ${f.subset} */
@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: block;
  src: url('/web/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
);

await writeFile(CSS_OUT, `${header}\n${blocks.join("\n\n")}\n`);

// A file left behind by an earlier vendoring (a dropped weight, a renamed family)
// would still ship in the binary. Name it rather than deleting it: removing bytes
// from the repo is the author's call, not this script's.
const written = new Set([...faces.map((f) => f.file), ...Object.keys(LICENSES)]);
const stale = (await readdir(FONT_DIR)).filter((f) => !written.has(f));
if (stale.length > 0) console.log(`stale, delete by hand: ${stale.join(", ")}`);

console.log(`wrote ${faces.length} woff2 (${total.toLocaleString("en-US")} bytes) + 2 OFL.txt`);
for (const f of faces) console.log(`  ${f.file.padEnd(46)} ${String(f.bytes).padStart(7)}  ${f.sha}`);
