// Code generated by cmd/cligen from api/openapi.json. DO NOT EDIT.

package cli

import (
	"fmt"
	"net/url"

	"github.com/spf13/cobra"
)

// generatedCommands returns the API-backed command tree built from the OpenAPI.
// clientFor resolves the server and token from the invoking command at run time.
func generatedCommands() []*cobra.Command {
	var roots []*cobra.Command

	roots = append(roots, func() *cobra.Command {
		cmd := &cobra.Command{
			Use:     "healthz",
			Short:   "Liveness and database-reachability probe",
			Long:    "Reports process health and the database leg, pinged through the Storage Gateway.",
			Example: "  omniglass healthz",
			Args:    cobra.ExactArgs(0),
			RunE: func(cmd *cobra.Command, args []string) error {
				path := fmt.Sprintf("/api/v1/healthz")
				return runAPICommand(cmd, "GET", path, nil)
			},
		}
		return cmd
	}())
	{
		parent := &cobra.Command{
			Use:   "auth",
			Short: "Commands for the auth resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "me",
				Short:   "The authenticated principal, its permissions, and grants",
				Long:    "Returns the caller's principal, flattened permissions (a UI hint and the fast-reject set), and grants. Requires authentication.",
				Example: "  omniglass auth me",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/me")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "component",
			Short: "Commands for the component resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fComponentType string
			var fDisplayName string
			var fLocation string
			var fName string
			var fParent string
			var fSystem string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a component",
				Long:    "Creates a component, optionally under a parent (a root needs an all-scoped grant), bound to a system and a location. Gated by component:create.",
				Example: "  omniglass component create --component-type component_type --name name",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components")
					body := map[string]any{}
					if cmd.Flags().Changed("component-type") {
						body["component_type"] = fComponentType
					}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location") {
						body["location"] = fLocation
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					if cmd.Flags().Changed("system") {
						body["system"] = fSystem
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fComponentType, "component-type", "", "A component_type id")
			_ = cmd.MarkFlagRequired("component-type")
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocation, "location", "", "Location name this component is placed at")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent component name; omit for a root component")
			cmd.Flags().StringVar(&fSystem, "system", "", "Primary system name this component belongs to")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a component",
				Long:    "Deletes a component, refused while it still has child components. Gated by component:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass component delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a component",
				Long:    "Fetches a component by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by component:read.",
				Example: "  omniglass component get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List components in scope",
				Long:    "Lists the components the caller may read, each filtered to its scope subtree. Gated by component:read.",
				Example: "  omniglass component list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fComponentType string
			var fDisplayName string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a component",
				Long:    "Patches a component's display_name or component_type. Gated by component:update; read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass component update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("component-type") {
						body["component_type"] = fComponentType
					}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fComponentType, "component-type", "", "")
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "location",
			Short: "Commands for the location resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocationType string
			var fName string
			var fParent string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a location",
				Long:    "Creates a location, optionally under a parent (a root needs an all-scoped grant). Gated by location:create.",
				Example: "  omniglass location create --location-type location_type --name name",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location-type") {
						body["location_type"] = fLocationType
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocationType, "location-type", "", "A location_type id (campus, building, ...)")
			_ = cmd.MarkFlagRequired("location-type")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent location name; omit for a root location")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a location",
				Long:    "Deletes a location, refused while it still has child locations. Gated by location:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass location delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a location",
				Long:    "Fetches a location by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by location:read.",
				Example: "  omniglass location get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List locations in scope",
				Long:    "Lists the locations the caller may read, each filtered to its scope subtree. Gated by location:read.",
				Example: "  omniglass location list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocationType string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a location",
				Long:    "Patches a location's display_name or location_type. Gated by location:update; the read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass location update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location-type") {
						body["location_type"] = fLocationType
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocationType, "location-type", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "location-type",
			Short: "Commands for the location-type resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List location types",
				Long:    "Lists the location_type registry (the shape-definers a location is classified by), ordered by rank. Populates the type picker on the location form. Gated by location:read.",
				Example: "  omniglass location-type list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/location-types")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "login",
			Short: "Commands for the login resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fPassword string
			var fUsername string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Log in with a username and password",
				Long:    "Verifies a human's password and sets an httpOnly session cookie. Public; a bad credential is a flat 401.",
				Example: "  omniglass login create --password password --username username",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/login")
					body := map[string]any{}
					if cmd.Flags().Changed("password") {
						body["password"] = fPassword
					}
					if cmd.Flags().Changed("username") {
						body["username"] = fUsername
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fPassword, "password", "", "")
			_ = cmd.MarkFlagRequired("password")
			cmd.Flags().StringVar(&fUsername, "username", "", "")
			_ = cmd.MarkFlagRequired("username")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "logout",
			Short: "Commands for the logout resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Log out the current session",
				Long:    "Revokes the session token and clears the cookie. Public.",
				Example: "  omniglass logout create",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/logout")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "role",
			Short: "Commands for the role resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List roles",
				Long:    "Lists the roles. Gated by the role:read capability.",
				Example: "  omniglass role list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/roles")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "statu",
			Short: "Commands for the statu resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "Whether the system has an owner yet",
				Long:    "Public: reports whether any owner has been bootstrapped, so the login screen can hide the bootstrap hint.",
				Example: "  omniglass statu list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/status")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "system",
			Short: "Commands for the system resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocation string
			var fName string
			var fParent string
			var fSystemType string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a system",
				Long:    "Creates a system, optionally under a parent (a root needs an all-scoped grant) and at a location. Gated by system:create.",
				Example: "  omniglass system create --name name --system-type system_type",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location") {
						body["location"] = fLocation
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					if cmd.Flags().Changed("system-type") {
						body["system_type"] = fSystemType
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocation, "location", "", "Location name this system is placed at")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent system name; omit for a root system")
			cmd.Flags().StringVar(&fSystemType, "system-type", "", "A system_type id")
			_ = cmd.MarkFlagRequired("system-type")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a system",
				Long:    "Deletes a system, refused while it still has child systems. Gated by system:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass system delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a system",
				Long:    "Fetches a system by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by system:read.",
				Example: "  omniglass system get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List systems in scope",
				Long:    "Lists the systems the caller may read, each filtered to its scope subtree. Gated by system:read.",
				Example: "  omniglass system list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fSystemType string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a system",
				Long:    "Patches a system's display_name or system_type. Gated by system:update; read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass system update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("system-type") {
						body["system_type"] = fSystemType
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fSystemType, "system-type", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	return roots
}
