// Code generated by cmd/cligen from api/openapi.json. DO NOT EDIT.

package cli

import (
	"fmt"
	"net/url"

	"github.com/spf13/cobra"
)

// generatedCommands returns the API-backed command tree built from the OpenAPI.
// clientFor resolves the server and token from the invoking command at run time.
func generatedCommands() []*cobra.Command {
	var roots []*cobra.Command

	roots = append(roots, func() *cobra.Command {
		cmd := &cobra.Command{
			Use:     "healthz",
			Short:   "Liveness and database-reachability probe",
			Long:    "Reports process health and the database leg, pinged through the Storage Gateway.",
			Example: "  omniglass healthz",
			Args:    cobra.ExactArgs(0),
			RunE: func(cmd *cobra.Command, args []string) error {
				path := fmt.Sprintf("/api/v1/healthz")
				return runAPICommand(cmd, "GET", path, nil)
			},
		}
		return cmd
	}())
	{
		parent := &cobra.Command{
			Use:   "audit-log",
			Short: "Commands for the audit-log resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List audit-trail events",
				Long:    "Recent audit-trail events, newest first, each with the actor and, for an impersonated action, the real actor behind it. Read-only; gated by audit:read:admin (admin/owner only, since the audit trail is admin-sensitive).",
				Example: "  omniglass audit-log list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/audit-log")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "auth",
			Short: "Commands for the auth resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fCurrentPassword string
			var fNewPassword string
			cmd := &cobra.Command{
				Use:     "change-password",
				Short:   "Change your own password",
				Long:    "Verifies the current password and sets a new one. Requires authentication; self-scoped.",
				Example: "  omniglass auth change-password --current-password current_password --new-password new_password",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/me:changePassword")
					body := map[string]any{}
					if cmd.Flags().Changed("current-password") {
						body["current_password"] = fCurrentPassword
					}
					if cmd.Flags().Changed("new-password") {
						body["new_password"] = fNewPassword
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fCurrentPassword, "current-password", "", "Your current password")
			_ = cmd.MarkFlagRequired("current-password")
			cmd.Flags().StringVar(&fNewPassword, "new-password", "", "The new password (at least 8 characters)")
			_ = cmd.MarkFlagRequired("new-password")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "me",
				Short:   "The authenticated principal, its permissions, and grants",
				Long:    "Returns the caller's principal, flattened permissions (a UI hint and the fast-reject set), and grants. Requires authentication.",
				Example: "  omniglass auth me",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/me")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			cmd := &cobra.Command{
				Use:     "update-profile",
				Short:   "Update your own profile",
				Long:    "Updates the caller's own display name (email is administrator-set). Requires authentication; self-scoped (edits only your own principal).",
				Example: "  omniglass auth update-profile",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/me")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "Your display name; empty clears it")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "component",
			Short: "Commands for the component resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fComponentType string
			var fDisplayName string
			var fLocation string
			var fName string
			var fParent string
			var fSystem string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a component",
				Long:    "Creates a component, optionally under a parent (a root needs an all-scoped grant), bound to a system and a location. Gated by component:create.",
				Example: "  omniglass component create --component-type component_type --name name",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components")
					body := map[string]any{}
					if cmd.Flags().Changed("component-type") {
						body["component_type"] = fComponentType
					}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location") {
						body["location"] = fLocation
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					if cmd.Flags().Changed("system") {
						body["system"] = fSystem
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fComponentType, "component-type", "", "A component_type id")
			_ = cmd.MarkFlagRequired("component-type")
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocation, "location", "", "Location name this component is placed at")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent component name; omit for a root component")
			cmd.Flags().StringVar(&fSystem, "system", "", "Primary system name this component belongs to")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a component",
				Long:    "Deletes a component, refused while it still has child components. Gated by component:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass component delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a component",
				Long:    "Fetches a component by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by component:read.",
				Example: "  omniglass component get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List components in scope",
				Long:    "Lists the components the caller may read, each filtered to its scope subtree. Gated by component:read.",
				Example: "  omniglass component list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fComponentType string
			var fDisplayName string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a component",
				Long:    "Patches a component's display_name or component_type. Gated by component:update; read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass component update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("component-type") {
						body["component_type"] = fComponentType
					}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fComponentType, "component-type", "", "")
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "effective-secret",
			Short: "Commands for the effective-secret resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list <name>",
				Short:   "Effective secrets for a component",
				Long:    "Resolves the secrets that cascade onto a component (global -> location -> system -> component, most-specific winning), each masked, winner and shadowed candidates. Gated by secret:read; the component must be in the caller's component read scope.",
				Example: "  omniglass effective-secret list <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/components/%s/effective-secrets", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "grant",
			Short: "Commands for the grant resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fRole string
			var fScopeId string
			var fScopeKind string
			var fScopeOp string
			cmd := &cobra.Command{
				Use:     "create <id>",
				Short:   "Grant a role to a group",
				Long:    "Assigns a role at a scope to a group; its members inherit it. Gated by principal_grant:create (all-scope). Refused (403) when the granted role's capabilities exceed the granter's own, exactly as for a direct grant. A duplicate is 409.",
				Example: "  omniglass grant create <id> --role role --scope-kind scope_kind",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s/grants", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("role") {
						body["role"] = fRole
					}
					if cmd.Flags().Changed("scope-id") {
						body["scope_id"] = fScopeId
					}
					if cmd.Flags().Changed("scope-kind") {
						body["scope_kind"] = fScopeKind
					}
					if cmd.Flags().Changed("scope-op") {
						body["scope_op"] = fScopeOp
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fRole, "role", "", "A role id (viewer, operator, admin, owner, or a custom role)")
			_ = cmd.MarkFlagRequired("role")
			cmd.Flags().StringVar(&fScopeId, "scope-id", "", "The scope root id; omit for the all scope")
			cmd.Flags().StringVar(&fScopeKind, "scope-kind", "", "The scope kind; 'all' confers the whole estate")
			_ = cmd.MarkFlagRequired("scope-kind")
			cmd.Flags().StringVar(&fScopeOp, "scope-op", "", "How the scope root matches the tree; moot for the all scope")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fRole string
			var fScopeId string
			var fScopeKind string
			var fScopeOp string
			cmd := &cobra.Command{
				Use:     "create <id>",
				Short:   "Grant a role to a principal",
				Long:    "Assigns a role at a scope to a principal. Gated by principal_grant:create (all-scope). Refused (403) when the granted role's capabilities exceed the granter's own (no promoting anyone, including yourself, to a higher tier such as owner). A duplicate is 409, an unknown role or bad scope 422.",
				Example: "  omniglass grant create <id> --role role --scope-kind scope_kind",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/%s/grants", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("role") {
						body["role"] = fRole
					}
					if cmd.Flags().Changed("scope-id") {
						body["scope_id"] = fScopeId
					}
					if cmd.Flags().Changed("scope-kind") {
						body["scope_kind"] = fScopeKind
					}
					if cmd.Flags().Changed("scope-op") {
						body["scope_op"] = fScopeOp
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fRole, "role", "", "A role id (viewer, operator, admin, owner, or a custom role)")
			_ = cmd.MarkFlagRequired("role")
			cmd.Flags().StringVar(&fScopeId, "scope-id", "", "The scope root id; omit for the all scope")
			cmd.Flags().StringVar(&fScopeKind, "scope-kind", "", "The scope kind; 'all' confers the whole estate")
			_ = cmd.MarkFlagRequired("scope-kind")
			cmd.Flags().StringVar(&fScopeOp, "scope-op", "", "How the scope root matches the tree: subtree (root + descendants, the default), subtree_excl_root (descendants only for update/delete, root kept for read/create), or self (the root row only). Moot for the all scope.")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <id> <grantId>",
				Short:   "Revoke a group grant",
				Long:    "Removes one grant from a group. Gated by principal_grant:delete (all-scope).",
				Example: "  omniglass grant delete <id> <grantId>",
				Args:    cobra.ExactArgs(2),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s/grants/%s", url.PathEscape(args[0]), url.PathEscape(args[1]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <id> <grantId>",
				Short:   "Revoke a grant",
				Long:    "Removes one grant from a principal. Gated by principal_grant:delete (all-scope). The last owner grant cannot be revoked.",
				Example: "  omniglass grant delete <id> <grantId>",
				Args:    cobra.ExactArgs(2),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/%s/grants/%s", url.PathEscape(args[0]), url.PathEscape(args[1]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list <id>",
				Short:   "List a group's grants",
				Long:    "The role x scope grants a group confers on its members. Gated by principal_group:read (all-scope).",
				Example: "  omniglass grant list <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s/grants", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "location",
			Short: "Commands for the location resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocationType string
			var fName string
			var fParent string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a location",
				Long:    "Creates a location, optionally under a parent (a root needs an all-scoped grant). Gated by location:create.",
				Example: "  omniglass location create --location-type location_type --name name",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location-type") {
						body["location_type"] = fLocationType
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocationType, "location-type", "", "A location_type id (campus, building, ...)")
			_ = cmd.MarkFlagRequired("location-type")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent location name; omit for a root location")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a location",
				Long:    "Deletes a location, refused while it still has child locations. Gated by location:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass location delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a location",
				Long:    "Fetches a location by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by location:read.",
				Example: "  omniglass location get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List locations in scope",
				Long:    "Lists the locations the caller may read, each filtered to its scope subtree. Gated by location:read.",
				Example: "  omniglass location list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocationType string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a location",
				Long:    "Patches a location's display_name or location_type. Gated by location:update; the read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass location update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location-type") {
						body["location_type"] = fLocationType
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocationType, "location-type", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "location-type",
			Short: "Commands for the location-type resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List location types",
				Long:    "Lists the location_type registry (the shape-definers a location is classified by), ordered by rank. Populates the type picker on the location form. Gated by location:read.",
				Example: "  omniglass location-type list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/location-types")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "login",
			Short: "Commands for the login resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fPassword string
			var fUsername string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Log in with a username and password",
				Long:    "Verifies a human's password and sets an httpOnly session cookie. Public; a bad credential is a flat 401, and a correct password against a disabled account is a distinct 403 so the screen can explain it.",
				Example: "  omniglass login create --password password --username username",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/login")
					body := map[string]any{}
					if cmd.Flags().Changed("password") {
						body["password"] = fPassword
					}
					if cmd.Flags().Changed("username") {
						body["username"] = fUsername
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fPassword, "password", "", "")
			_ = cmd.MarkFlagRequired("password")
			cmd.Flags().StringVar(&fUsername, "username", "", "")
			_ = cmd.MarkFlagRequired("username")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "logout",
			Short: "Commands for the logout resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Log out the current session",
				Long:    "Revokes the session token and clears the cookie. Public.",
				Example: "  omniglass logout create",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/logout")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "me",
			Short: "Commands for the me resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "stopImpersonation",
				Short:   "Stop the current impersonation session",
				Long:    "Revokes the impersonation session presented by the request token, ending the view-as / act-as. Requires an impersonation token.",
				Example: "  omniglass me stopImpersonation",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/me:stopImpersonation")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "member",
			Short: "Commands for the member resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fPrincipalId string
			cmd := &cobra.Command{
				Use:     "create <id>",
				Short:   "Add a member to a group",
				Long:    "Adds a principal to a group; its members inherit the group's grants. Gated by principal_group:update (all-scope). Idempotent.",
				Example: "  omniglass member create <id> --principal-id principal_id",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s/members", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("principal-id") {
						body["principal_id"] = fPrincipalId
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fPrincipalId, "principal-id", "", "The principal to add to the group")
			_ = cmd.MarkFlagRequired("principal-id")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <id> <principalId>",
				Short:   "Remove a member from a group",
				Long:    "Removes a principal from a group; it stops inheriting the group's grants. Gated by principal_group:update (all-scope).",
				Example: "  omniglass member delete <id> <principalId>",
				Args:    cobra.ExactArgs(2),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s/members/%s", url.PathEscape(args[0]), url.PathEscape(args[1]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list <id>",
				Short:   "List a group's members",
				Long:    "The principals in a group. Gated by principal_group:read (all-scope).",
				Example: "  omniglass member list <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s/members", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "principal",
			Short: "Commands for the principal resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "archive",
				Short:   "Archive a principal",
				Long:    "Soft-deletes a principal: it is hidden from the directory, can no longer authenticate, and its rows stay intact, reversibly (restore) until purged. Gated by principal:archive (all-scope). The last active owner cannot be archived.",
				Example: "  omniglass principal archive",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/{id}:archive")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fEmail string
			var fPassword string
			var fUsername string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a human principal",
				Long:    "Creates a human principal with an optional initial password. Gated by principal:create (all-scope). The new principal holds no grants; assign roles separately.",
				Example: "  omniglass principal create --username username",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("email") {
						body["email"] = fEmail
					}
					if cmd.Flags().Changed("password") {
						body["password"] = fPassword
					}
					if cmd.Flags().Changed("username") {
						body["username"] = fUsername
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fEmail, "email", "", "")
			cmd.Flags().StringVar(&fPassword, "password", "", "Optional initial password; the user changes it after signing in")
			cmd.Flags().StringVar(&fUsername, "username", "", "Unique sign-in name (lowercase letters, digits, and . _ -)")
			_ = cmd.MarkFlagRequired("username")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "disable",
				Short:   "Disable a principal",
				Long:    "Soft-disables a principal so it can no longer authenticate; its audit trail is kept. Gated by principal:update (all-scope). The last active owner cannot be disabled.",
				Example: "  omniglass principal disable",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/{id}:disable")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "enable",
				Short:   "Enable a principal",
				Long:    "Re-enables a disabled principal, restoring its ability to authenticate. Gated by principal:update (all-scope).",
				Example: "  omniglass principal enable",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/{id}:enable")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <id>",
				Short:   "Get a principal",
				Long:    "Fetches one principal by id with its profile and grants. Gated by principal:read (all-scope).",
				Example: "  omniglass principal get <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDurationMinutes string
			var fMode string
			cmd := &cobra.Command{
				Use:     "impersonate",
				Short:   "Impersonate a principal (view-as or act-as)",
				Long:    "Mints a bounded, revocable token to view as (read-only) or act as (full) the target. Gated by principal:impersonate (all-scope). Refused on self, on an owner target (owners are un-impersonatable by anyone), when it would grant a capability the caller lacks (the escalation guard), or from within an existing impersonation.",
				Example: "  omniglass principal impersonate --mode mode",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/{id}:impersonate")
					body := map[string]any{}
					if cmd.Flags().Changed("duration-minutes") {
						body["duration_minutes"] = fDurationMinutes
					}
					if cmd.Flags().Changed("mode") {
						body["mode"] = fMode
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDurationMinutes, "duration-minutes", "", "Session lifetime in minutes (default 30, max 1440)")
			cmd.Flags().StringVar(&fMode, "mode", "", "view_as is read-only; act_as is full, with mutations attributed to both the real actor and the impersonated principal")
			_ = cmd.MarkFlagRequired("mode")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List principals",
				Long:    "Lists all principals (humans and service accounts) with their grants. Gated by principal:read, which confers access only at all-scope.",
				Example: "  omniglass principal list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "purge",
				Short:   "Purge a principal",
				Long:    "Hard-deletes an archived principal and its owned rows (profile, credentials, grants, memberships); the audit trail is preserved. Irreversible. Gated by principal:purge (admin-sensitive, all-scope), and the principal must be archived first.",
				Example: "  omniglass principal purge",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/{id}:purge")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "restore",
				Short:   "Restore a principal",
				Long:    "Reverses an archive: the account is restored to active and can authenticate again. Gated by principal:archive (all-scope).",
				Example: "  omniglass principal restore",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/{id}:restore")
					return runAPICommand(cmd, "POST", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fEmail string
			var fUsername string
			cmd := &cobra.Command{
				Use:     "update <id>",
				Short:   "Update a principal",
				Long:    "Updates a human principal's display name, email, and username. Gated by principal:update (all-scope). Renaming is safe: nothing keys on the username.",
				Example: "  omniglass principal update <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principals/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("email") {
						body["email"] = fEmail
					}
					if cmd.Flags().Changed("username") {
						body["username"] = fUsername
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "Display name; empty clears it")
			cmd.Flags().StringVar(&fEmail, "email", "", "Email; empty clears it")
			cmd.Flags().StringVar(&fUsername, "username", "", "Sign-in name (lowercase letters, digits, and . _ -); renaming is safe")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "principal-group",
			Short: "Commands for the principal-group resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fDescription string
			var fDisplayName string
			var fName string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a principal group",
				Long:    "Creates a principal group. Gated by principal_group:create (all-scope). A duplicate name is 409.",
				Example: "  omniglass principal-group create --name name",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups")
					body := map[string]any{}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDescription, "description", "", "")
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fName, "name", "", "Unique group name (lowercase letters, digits, and . _ -)")
			_ = cmd.MarkFlagRequired("name")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <id>",
				Short:   "Delete a principal group",
				Long:    "Removes a group and, by cascade, its memberships and grants. Gated by principal_group:delete (all-scope).",
				Example: "  omniglass principal-group delete <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <id>",
				Short:   "Get a principal group",
				Long:    "One principal group by id. Gated by principal_group:read (all-scope).",
				Example: "  omniglass principal-group get <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List principal groups",
				Long:    "Every principal group. Gated by principal_group:read (all-scope).",
				Example: "  omniglass principal-group list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDescription string
			var fDisplayName string
			var fName string
			cmd := &cobra.Command{
				Use:     "update <id>",
				Short:   "Update a principal group",
				Long:    "Updates a group's name and presentational fields. Gated by principal_group:update (all-scope). A duplicate name is 409.",
				Example: "  omniglass principal-group update <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/principal-groups/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDescription, "description", "", "Description; empty clears it")
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "Display name; empty clears it")
			cmd.Flags().StringVar(&fName, "name", "", "Group name (lowercase letters, digits, and . _ -); renaming is safe")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "role",
			Short: "Commands for the role resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List roles",
				Long:    "Lists the roles with their metadata and effective (flattened) permissions. Gated by the role:read capability.",
				Example: "  omniglass role list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/roles")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "secret",
			Short: "Commands for the secret resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fFields string
			var fName string
			var fOwner string
			var fOwnerKind string
			var fSecretType string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a secret",
				Long:    "Seals a secret at an owner scope (a global secret needs an all-scoped grant). Fields are validated and encrypted against the type shape. Gated by secret:create.",
				Example: "  omniglass secret create --fields fields --name name --owner-kind owner_kind --secret-type secret_type",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/secrets")
					body := map[string]any{}
					if cmd.Flags().Changed("fields") {
						body["fields"] = fFields
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("owner") {
						body["owner"] = fOwner
					}
					if cmd.Flags().Changed("owner-kind") {
						body["owner_kind"] = fOwnerKind
					}
					if cmd.Flags().Changed("secret-type") {
						body["secret_type"] = fSecretType
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fFields, "fields", "", "The operator field map, validated against the type shape")
			_ = cmd.MarkFlagRequired("fields")
			cmd.Flags().StringVar(&fName, "name", "", "The cascade key; unique per owner")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fOwner, "owner", "", "The owning entity's name; omit for a global secret")
			cmd.Flags().StringVar(&fOwnerKind, "owner-kind", "", "Which tier owns this secret")
			_ = cmd.MarkFlagRequired("owner-kind")
			cmd.Flags().StringVar(&fSecretType, "secret-type", "", "A secret_type id")
			_ = cmd.MarkFlagRequired("secret-type")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <id>",
				Short:   "Delete a secret",
				Long:    "Removes a secret by id. Gated by secret:delete; read and delete scopes on the owner drive the 404 versus 403 split.",
				Example: "  omniglass secret delete <id>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/secrets/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List secrets (admin directory)",
				Long:    "Lists every secret with masked fields. Requires an all-scope read; the scoped, per-component view is the effective-secrets route. Gated by secret:read.",
				Example: "  omniglass secret list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/secrets")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "secret-type",
			Short: "Commands for the secret-type resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List secret types",
				Long:    "Lists the secret_type shapes a secret can take, for the create form. Gated by secret:read.",
				Example: "  omniglass secret-type list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/secret-types")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "statu",
			Short: "Commands for the statu resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "Whether the system has an owner yet",
				Long:    "Public: reports whether any owner has been bootstrapped, so the login screen can hide the bootstrap hint.",
				Example: "  omniglass statu list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/status")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "system",
			Short: "Commands for the system resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocation string
			var fName string
			var fParent string
			var fSystemType string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a system",
				Long:    "Creates a system, optionally under a parent (a root needs an all-scoped grant) and at a location. Gated by system:create.",
				Example: "  omniglass system create --name name --system-type system_type",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location") {
						body["location"] = fLocation
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					if cmd.Flags().Changed("system-type") {
						body["system_type"] = fSystemType
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocation, "location", "", "Location name this system is placed at")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent system name; omit for a root system")
			cmd.Flags().StringVar(&fSystemType, "system-type", "", "A system_type id")
			_ = cmd.MarkFlagRequired("system-type")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a system",
				Long:    "Deletes a system, refused while it still has child systems. Gated by system:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass system delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a system",
				Long:    "Fetches a system by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by system:read.",
				Example: "  omniglass system get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List systems in scope",
				Long:    "Lists the systems the caller may read, each filtered to its scope subtree. Gated by system:read.",
				Example: "  omniglass system list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fSystemType string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a system",
				Long:    "Patches a system's display_name or system_type. Gated by system:update; read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass system update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/systems/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("system-type") {
						body["system_type"] = fSystemType
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fSystemType, "system-type", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	return roots
}
