// Code generated by cmd/cligen from api/openapi.json. DO NOT EDIT.

package cli

import (
	"fmt"
	"net/url"

	"github.com/spf13/cobra"
)

// generatedCommands returns the API-backed command tree built from the OpenAPI.
// clientFor resolves the server and token from the invoking command at run time.
func generatedCommands() []*cobra.Command {
	var roots []*cobra.Command

	roots = append(roots, func() *cobra.Command {
		cmd := &cobra.Command{
			Use:     "healthz",
			Short:   "Liveness and database-reachability probe",
			Long:    "Reports process health and the database leg, pinged through the Storage Gateway.",
			Example: "  omniglass healthz",
			Args:    cobra.ExactArgs(0),
			RunE: func(cmd *cobra.Command, args []string) error {
				path := fmt.Sprintf("/api/v1/healthz")
				return runAPICommand(cmd, "GET", path, nil)
			},
		}
		return cmd
	}())
	{
		parent := &cobra.Command{
			Use:   "auth",
			Short: "Commands for the auth resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "me",
				Short:   "The authenticated principal, its permissions, and grants",
				Long:    "Returns the caller's principal, flattened permissions (a UI hint and the fast-reject set), and grants. Requires authentication.",
				Example: "  omniglass auth me",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/auth/me")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "location",
			Short: "Commands for the location resource",
		}
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocationType string
			var fName string
			var fParent string
			cmd := &cobra.Command{
				Use:     "create",
				Short:   "Create a location",
				Long:    "Creates a location, optionally under a parent (a root needs an all-scoped grant). Gated by location:create.",
				Example: "  omniglass location create --location-type location_type --name name",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations")
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location-type") {
						body["location_type"] = fLocationType
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("parent") {
						body["parent"] = fParent
					}
					return runAPICommand(cmd, "POST", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocationType, "location-type", "", "A location_type id (campus, building, ...)")
			_ = cmd.MarkFlagRequired("location-type")
			cmd.Flags().StringVar(&fName, "name", "", "Globally unique name (the address)")
			_ = cmd.MarkFlagRequired("name")
			cmd.Flags().StringVar(&fParent, "parent", "", "Parent location name; omit for a root location")
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "delete <name>",
				Short:   "Delete a location",
				Long:    "Deletes a location, refused while it still has child locations. Gated by location:delete; read and delete scopes drive the 404 versus 403 split.",
				Example: "  omniglass location delete <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "DELETE", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "get <name>",
				Short:   "Get a location",
				Long:    "Fetches a location by name within the caller's read scope. Out of scope is a non-disclosing 404. Gated by location:read.",
				Example: "  omniglass location get <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List locations in scope",
				Long:    "Lists the locations the caller may read, each filtered to its scope subtree. Gated by location:read.",
				Example: "  omniglass location list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		parent.AddCommand(func() *cobra.Command {
			var fDisplayName string
			var fLocationType string
			cmd := &cobra.Command{
				Use:     "update <name>",
				Short:   "Update a location",
				Long:    "Patches a location's display_name or location_type. Gated by location:update; the read and update scopes drive the 404 versus 403 split.",
				Example: "  omniglass location update <name>",
				Args:    cobra.ExactArgs(1),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/locations/%s", url.PathEscape(args[0]))
					body := map[string]any{}
					if cmd.Flags().Changed("display-name") {
						body["display_name"] = fDisplayName
					}
					if cmd.Flags().Changed("location-type") {
						body["location_type"] = fLocationType
					}
					return runAPICommand(cmd, "PATCH", path, body)
				},
			}
			cmd.Flags().StringVar(&fDisplayName, "display-name", "", "")
			cmd.Flags().StringVar(&fLocationType, "location-type", "", "")
			return cmd
		}())
		roots = append(roots, parent)
	}
	{
		parent := &cobra.Command{
			Use:   "role",
			Short: "Commands for the role resource",
		}
		parent.AddCommand(func() *cobra.Command {
			cmd := &cobra.Command{
				Use:     "list",
				Short:   "List roles",
				Long:    "Lists the roles. Gated by the role:read capability.",
				Example: "  omniglass role list",
				Args:    cobra.ExactArgs(0),
				RunE: func(cmd *cobra.Command, args []string) error {
					path := fmt.Sprintf("/api/v1/roles")
					return runAPICommand(cmd, "GET", path, nil)
				},
			}
			return cmd
		}())
		roots = append(roots, parent)
	}
	return roots
}
