// Command docsgen renders the CLI reference page from the live cobra command
// tree (internal/cli.Root), the docs arm of the generation pipeline after the
// spec, the CLI, and the typed client. It walks the real command surface, so the
// published reference can never drift from the binary: a new API operation is a
// new generated command and, on the next `make gen`, a new entry here. The
// output is committed and reviewed like any generated code; do not hand-edit it.
package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hyperscaleav/omniglass/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const dst = "docs/src/content/docs/reference/cli/index.md"

func main() {
	root := cli.Root("(version)")

	var b bytes.Buffer
	writeHeader(&b)
	writeGlobalFlags(&b, root)

	for _, c := range sortedVisible(root.Commands()) {
		render(&b, c, 2)
	}

	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		log.Fatalf("docsgen: mkdir: %v", err)
	}
	if err := os.WriteFile(dst, b.Bytes(), 0o644); err != nil {
		log.Fatalf("docsgen: write: %v", err)
	}
	log.Printf("wrote %s", dst)
}

func writeHeader(b *bytes.Buffer) {
	b.WriteString(`---
title: CLI reference
description: "Every omniglass CLI command, generated from the live command tree so it never drifts from the binary."
---

<!-- Generated by cmd/docsgen from the cobra command tree. Do not edit by hand; run ` + "`make gen`" + `. -->

Every ` + "`omniglass`" + ` command, generated from the binary's own command tree. The data commands
are generated from the [API](/reference/api/) (` + "`make gen`" + `), so this reference is a faithful mirror of
what the server exposes. For the narrative, connecting, authenticating, and the generated-versus-
hand-written split, see [the CLI guide](/guides/cli/).

`)
}

func writeGlobalFlags(b *bytes.Buffer, root *cobra.Command) {
	pf := root.PersistentFlags()
	if !pf.HasFlags() {
		return
	}
	b.WriteString("## Global flags\n\nEvery command accepts these, each with an environment-variable default:\n\n")
	writeFlagTable(b, pf)
}

// render walks one command. A command with subcommands becomes a heading and its
// children recurse a level deeper; a runnable leaf becomes a detail block.
func render(b *bytes.Buffer, cmd *cobra.Command, depth int) {
	if cmd.HasAvailableSubCommands() {
		heading(b, depth, "`"+cmd.CommandPath()+"`")
		if cmd.Short != "" {
			b.WriteString(cmd.Short + "\n\n")
		}
		for _, c := range sortedVisible(cmd.Commands()) {
			render(b, c, depth+1)
		}
		return
	}
	writeLeaf(b, cmd, depth)
}

func writeLeaf(b *bytes.Buffer, cmd *cobra.Command, depth int) {
	heading(b, depth, "`"+cmd.CommandPath()+"`")
	if cmd.Short != "" {
		b.WriteString(cmd.Short + "\n\n")
	}
	b.WriteString("```\n" + cmd.UseLine() + "\n```\n\n")
	if long := strings.TrimSpace(cmd.Long); long != "" && long != strings.TrimSpace(cmd.Short) {
		b.WriteString(long + "\n\n")
	}
	if f := cmd.NonInheritedFlags(); f.HasFlags() {
		writeFlagTable(b, f)
	}
	if ex := strings.TrimSpace(cmd.Example); ex != "" {
		b.WriteString("Example:\n\n```sh\n" + ex + "\n```\n\n")
	}
}

func writeFlagTable(b *bytes.Buffer, fs *pflag.FlagSet) {
	b.WriteString("| Flag | Type | Default | Description |\n|---|---|---|---|\n")
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name += ", `-" + f.Shorthand + "`"
		}
		def := f.DefValue
		if def == "" {
			def = "(none)"
		} else {
			def = "`" + def + "`"
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", name, f.Value.Type(), def, oneLine(f.Usage)))
	})
	b.WriteString("\n")
}

func heading(b *bytes.Buffer, depth int, text string) {
	if depth > 6 {
		depth = 6
	}
	b.WriteString(strings.Repeat("#", depth) + " " + text + "\n\n")
}

// sortedVisible returns the runnable, non-utility subcommands in name order.
func sortedVisible(cmds []*cobra.Command) []*cobra.Command {
	out := make([]*cobra.Command, 0, len(cmds))
	for _, c := range cmds {
		if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
