package label

import (
	"encoding/json"
	"fmt"
)

// The generated rule-language artifact: FactsJSON renders the closed function
// set into docs/src/generated/label.json, the file the docs render the rule
// language's table from rather than typing it out (#701). Same drift discipline
// as the seed and identity facts (a committed artifact plus a test that
// re-renders it), and no input beyond this package: [ruleFuncs] is the source
// and the FuncMap, FuncNames and the AST allowlist are the other three readers
// of it.
//
// The examples are rendered THROUGH the engine on the way out, so a row in the
// published table is an execution rather than an assertion about one.

type factsFunc struct {
	Name       string `json:"name"`
	Summary    string `json:"summary"`
	ExampleIn  string `json:"example_in"`
	ExampleOut string `json:"example_out"`
}

type labelFactsDoc struct {
	Comment   string      `json:"//"`
	Functions []factsFunc `json:"functions"`
	Builtins  []string    `json:"builtins"`
	MaxLen    int         `json:"max_len"`
}

// FactsJSON renders the rule-language facts document. Deterministic: the
// functions keep their documented order and the builtins keep theirs. The
// trailing newline makes the committed file POSIX-clean.
func FactsJSON() ([]byte, error) {
	doc := labelFactsDoc{
		Comment: "generated by make gen (cmd/labelgen); do not edit",
		MaxLen:  MaxLen,
	}
	for _, f := range ruleFuncs {
		got, err := renderExample(f)
		if err != nil {
			return nil, err
		}
		doc.Functions = append(doc.Functions, factsFunc{
			Name: f.Name, Summary: f.Summary,
			ExampleIn: f.ExampleIn, ExampleOut: got,
		})
	}
	doc.Builtins = append(doc.Builtins, allowedBuiltins...)

	out, err := json.MarshalIndent(doc, "", " ")
	if err != nil {
		return nil, fmt.Errorf("label facts: marshal: %w", err)
	}
	return append(out, '\n'), nil
}

// renderExample runs one function's documented input through a real rule on the
// dictionary-less engine, which is what makes the published example a fact. The
// dictionary is left out deliberately: what `title` does to a word in an
// operator's acronym list is that fleet's business, and a shipped table that
// showed one fleet's answer would be wrong everywhere else.
func renderExample(f ruleFunc) (string, error) {
	rule, err := Basic.Parse("{{." + exampleKey + " | " + f.Name + "}}")
	if err != nil {
		return "", fmt.Errorf("label facts: %s: %w", f.Name, err)
	}
	got, err := rule.Render(Data{exampleKey: f.ExampleIn})
	if err != nil {
		return "", fmt.Errorf("label facts: %s: %w", f.Name, err)
	}
	return got, nil
}

// exampleKey is the fact name the rendered examples read from. It is a real key
// on no entity: an example demonstrates a FUNCTION, and naming a live one would
// invite the table to be read as a claim about which facts a rule can reach.
const exampleKey = "Example"
