// Native Omniglass telemetry wire format. A node ships a collected batch as an
// Event (protobuf) over JetStream to og.v1.telemetry.<node>; the server's ingest
// consumer decodes it, binds the owner from the task's interface, and writes the
// typed samples. This is the platform's own wire (not OTLP): it fits the property
// taxonomy directly. Checkpoint 3 carries ONLY the Event and Sample messages;
// there is no gRPC service (the Event is a NATS message, not an RPC).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/og/v1/event.proto

package ogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is one batch of measurements a task collected, already normalized to the
// platform's property-name vocabulary. The node stamps NO component identity:
// the server binds the owner at ingest from the task's interface (task_id ->
// interface -> component). The node's only identity assertion is the subject (its
// own name, carried as node_id) plus the task_id.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the identity of the task that produced this batch. The server
	// resolves the owner (and confines the node to its own tasks) from it.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// node_id is the edge process that ran the task. Provenance for "where did this
	// run"; the authoritative node identity is the publishing subject.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// ts is the task-side timestamp for the batch. Per-sample Sample.ts overrides
	// this when set.
	Ts *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// labels are batch-level dimensional metadata common to every sample. Not
	// persisted in checkpoint 3 (only the typed sample row lands).
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// samples is the observations in this batch (a tcp probe carries tcp.open and,
	// when open, tcp.connect_time).
	Samples []*Sample `protobuf:"bytes,5,rep,name=samples,proto3" json:"samples,omitempty"`
	// raw is the original wire payload, preserved verbatim for replay. Empty for
	// the inline tcp probe (no protocol payload). Raw-Event persistence is deferred
	// to a later checkpoint.
	Raw           []byte `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_og_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_og_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_og_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Event) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Event) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

// Sample is one observation: a registry-resolved property name plus a typed value.
// The registry (property_type) says the kind and value type; the ingest consumer
// validates the name (reject-not-project) before writing.
type Sample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the canonical property name (e.g. "tcp.open"). Validated against
	// property_type at ingest; an unregistered name is dropped.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value carries the observation. The oneof keeps the wire compact and typed.
	// The tcp probe populates double_value.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Sample_IntValue
	//	*Sample_DoubleValue
	//	*Sample_StringValue
	//	*Sample_JsonValue
	Value isSample_Value `protobuf_oneof:"value"`
	// ts is the per-sample timestamp; defaults to Event.ts when unset.
	Ts *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	// labels are sample-specific dimensional metadata (e.g. the reason). Not
	// persisted in checkpoint 3.
	Labels        map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_proto_og_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_og_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proto_og_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *Sample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sample) GetValue() isSample_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Sample) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Sample_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Sample) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Sample_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Sample) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Sample_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Sample) GetJsonValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Sample_JsonValue); ok {
			return x.JsonValue
		}
	}
	return nil
}

func (x *Sample) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Sample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type isSample_Value interface {
	isSample_Value()
}

type Sample_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Sample_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Sample_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Sample_JsonValue struct {
	JsonValue []byte `protobuf:"bytes,5,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*Sample_IntValue) isSample_Value() {}

func (*Sample_DoubleValue) isSample_Value() {}

func (*Sample_StringValue) isSample_Value() {}

func (*Sample_JsonValue) isSample_Value() {}

var File_proto_og_v1_event_proto protoreflect.FileDescriptor

const file_proto_og_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x17proto/og/v1/event.proto\x12\x05og.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n" +
	"\x05Event\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x120\n" +
	"\x06labels\x18\x04 \x03(\v2\x18.og.v1.Event.LabelsEntryR\x06labels\x12'\n" +
	"\asamples\x18\x05 \x03(\v2\r.og.v1.SampleR\asamples\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\fR\x03raw\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x02\n" +
	"\x06Sample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x05 \x01(\fH\x00R\tjsonValue\x12*\n" +
	"\x02ts\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x121\n" +
	"\x06labels\x18\a \x03(\v2\x19.og.v1.Sample.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05valueB4Z2github.com/hyperscaleav/omniglass/proto/og/v1;ogv1b\x06proto3"

var (
	file_proto_og_v1_event_proto_rawDescOnce sync.Once
	file_proto_og_v1_event_proto_rawDescData []byte
)

func file_proto_og_v1_event_proto_rawDescGZIP() []byte {
	file_proto_og_v1_event_proto_rawDescOnce.Do(func() {
		file_proto_og_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_og_v1_event_proto_rawDesc), len(file_proto_og_v1_event_proto_rawDesc)))
	})
	return file_proto_og_v1_event_proto_rawDescData
}

var file_proto_og_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_og_v1_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: og.v1.Event
	(*Sample)(nil),                // 1: og.v1.Sample
	nil,                           // 2: og.v1.Event.LabelsEntry
	nil,                           // 3: og.v1.Sample.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_og_v1_event_proto_depIdxs = []int32{
	4, // 0: og.v1.Event.ts:type_name -> google.protobuf.Timestamp
	2, // 1: og.v1.Event.labels:type_name -> og.v1.Event.LabelsEntry
	1, // 2: og.v1.Event.samples:type_name -> og.v1.Sample
	4, // 3: og.v1.Sample.ts:type_name -> google.protobuf.Timestamp
	3, // 4: og.v1.Sample.labels:type_name -> og.v1.Sample.LabelsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_og_v1_event_proto_init() }
func file_proto_og_v1_event_proto_init() {
	if File_proto_og_v1_event_proto != nil {
		return
	}
	file_proto_og_v1_event_proto_msgTypes[1].OneofWrappers = []any{
		(*Sample_IntValue)(nil),
		(*Sample_DoubleValue)(nil),
		(*Sample_StringValue)(nil),
		(*Sample_JsonValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_og_v1_event_proto_rawDesc), len(file_proto_og_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_og_v1_event_proto_goTypes,
		DependencyIndexes: file_proto_og_v1_event_proto_depIdxs,
		MessageInfos:      file_proto_og_v1_event_proto_msgTypes,
	}.Build()
	File_proto_og_v1_event_proto = out.File
	file_proto_og_v1_event_proto_goTypes = nil
	file_proto_og_v1_event_proto_depIdxs = nil
}
