// Native Omniglass telemetry wire format. A node ships a collected batch as a
// TelemetryBatch (protobuf) over JetStream to og.v1.telemetry.<node>; the server's
// ingest consumer decodes it, binds the owner from the task's interface, and writes
// the typed samples. This is the platform's own wire (not OTLP): it fits the property
// taxonomy directly. There is no gRPC service (a batch is a NATS message, not an RPC).
//
// The batch is deliberately NOT called an Event. An event in this platform is a
// semantic occurrence (event_type-registered, with an origin, see ADR-0066); a batch
// is the envelope that carries samples and raw log lines, and will carry natively
// caught events too. Naming the envelope after one of its passengers is what the
// rename in #424 corrected.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/og/v1/telemetry.proto

package ogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryBatch is one batch a task collected, already normalized to the platform's
// property-name vocabulary. The node stamps NO component identity: the server binds
// the owner at ingest from the task's interface (task_id -> interface -> component).
// The node's only identity assertion is the subject (its own name, carried as
// node_id) plus the task_id.
type TelemetryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the identity of the task that produced this batch. The server
	// resolves the owner (and confines the node to its own tasks) from it.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// node_id is the edge process that ran the task. Provenance for "where did this
	// run"; the authoritative node identity is the publishing subject.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// ts is the batch-side timestamp. Per-sample Sample.ts overrides this when set.
	Ts *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// labels are batch-level dimensional metadata common to every sample. Not
	// persisted in checkpoint 3 (only the typed sample row lands).
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// samples is the observations in this batch (a tcp probe carries tcp.open and,
	// when open, tcp.connect_time).
	Samples []*Sample `protobuf:"bytes,5,rep,name=samples,proto3" json:"samples,omitempty"`
	// raw is the original wire payload, preserved verbatim for replay. Empty for
	// the inline tcp probe (no protocol payload). Raw-batch persistence is deferred
	// to a later checkpoint.
	Raw []byte `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	// logs is the raw log lines in this batch (ADR-0066): untyped arrival, not
	// registry-resolved samples. The consumer writes them to log_line, owner-confined
	// like samples. A node's self-logs ride here.
	Logs []*LogLine `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`
	// owner is the estate address this batch belongs to, set ONLY on the API push
	// lane (og.v1.api.telemetry), where the route already authorized the caller
	// against it. It is believed because of the subject the batch arrived on, never
	// because the field is populated: a batch on og.v1.telemetry.<node> that sets
	// owner is REJECTED, since a node's owner is the server's to resolve from the
	// task's interface, not the node's to assert.
	Owner *Owner `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	// source is who observed this batch ("webex-cloud", "manual"), the provenance
	// recorded on every row it lands. The node lane leaves it empty and the server
	// fills it from the task's interface_type; a push has no interface, so without
	// this its rows would be unattributable.
	Source        string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_proto_og_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TelemetryBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryBatch) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TelemetryBatch) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TelemetryBatch) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *TelemetryBatch) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *TelemetryBatch) GetLogs() []*LogLine {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *TelemetryBatch) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *TelemetryBatch) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Owner is an exclusive-arc address: which kind of estate entity owns the batch,
// and which one. Only the API lane sets it (see TelemetryBatch.owner).
type Owner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the arc: component, system, location, or node.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// ref addresses the entity within that kind, by name or id.
	Ref           string `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_proto_og_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Owner) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Owner) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Sample is one observation: a registry-resolved property name plus a typed value.
// The registry (property_type) says the kind and value type; the ingest consumer
// validates the name (reject-not-project) before writing.
type Sample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the canonical property name (e.g. "tcp.open"). Validated against
	// property_type at ingest; an unregistered name is dropped.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value carries the observation. The oneof keeps the wire compact and typed.
	// The tcp probe populates double_value.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Sample_IntValue
	//	*Sample_DoubleValue
	//	*Sample_StringValue
	//	*Sample_JsonValue
	Value isSample_Value `protobuf_oneof:"value"`
	// ts is the per-sample timestamp; defaults to the batch ts when unset.
	Ts *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	// instance discriminates many values of ONE property name on one owner (three
	// fan speeds, per-port counters), the first-class dimension of the data model
	// (instance text NOT NULL DEFAULT ”). The node lane leaves it empty and the
	// server fills it from the interface name, which doubles as the discriminator
	// there; a push has no interface, so without this a caller could not express
	// per-instance data at all.
	Instance string `protobuf:"bytes,8,opt,name=instance,proto3" json:"instance,omitempty"`
	// labels are sample-specific dimensional metadata (e.g. the reason). Not
	// persisted in checkpoint 3.
	Labels        map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proto_og_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Sample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sample) GetValue() isSample_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Sample) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Sample_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Sample) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Sample_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Sample) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Sample_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Sample) GetJsonValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Sample_JsonValue); ok {
			return x.JsonValue
		}
	}
	return nil
}

func (x *Sample) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Sample) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Sample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type isSample_Value interface {
	isSample_Value()
}

type Sample_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Sample_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Sample_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Sample_JsonValue struct {
	JsonValue []byte `protobuf:"bytes,5,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*Sample_IntValue) isSample_Value() {}

func (*Sample_DoubleValue) isSample_Value() {}

func (*Sample_StringValue) isSample_Value() {}

func (*Sample_JsonValue) isSample_Value() {}

// LogLine is one raw log line off the ingest lane (ADR-0066): untyped text, not a
// registry-resolved Sample. The consumer writes it to log_line, owner-confined to
// the publishing node (self-logs) or the task's component. severity and facility
// are the retention/routing axes; attributes and labels are freeform JSON.
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Facility      string                 `protobuf:"bytes,4,opt,name=facility,proto3" json:"facility,omitempty"`
	Attributes    []byte                 `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Labels        []byte                 `protobuf:"bytes,6,opt,name=labels,proto3" json:"labels,omitempty"`
	CorrelationId string                 `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_og_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_og_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogLine) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogLine) GetFacility() string {
	if x != nil {
		return x.Facility
	}
	return ""
}

func (x *LogLine) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogLine) GetLabels() []byte {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LogLine) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LogLine) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_proto_og_v1_telemetry_proto protoreflect.FileDescriptor

const file_proto_og_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/og/v1/telemetry.proto\x12\x05og.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x02\n" +
	"\x0eTelemetryBatch\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x129\n" +
	"\x06labels\x18\x04 \x03(\v2!.og.v1.TelemetryBatch.LabelsEntryR\x06labels\x12'\n" +
	"\asamples\x18\x05 \x03(\v2\r.og.v1.SampleR\asamples\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\fR\x03raw\x12\"\n" +
	"\x04logs\x18\a \x03(\v2\x0e.og.v1.LogLineR\x04logs\x12\"\n" +
	"\x05owner\x18\b \x01(\v2\f.og.v1.OwnerR\x05owner\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x05Owner\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"\xe5\x02\n" +
	"\x06Sample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x05 \x01(\fH\x00R\tjsonValue\x12*\n" +
	"\x02ts\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1a\n" +
	"\binstance\x18\b \x01(\tR\binstance\x121\n" +
	"\x06labels\x18\a \x03(\v2\x19.og.v1.Sample.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05value\"\xfe\x01\n" +
	"\aLogLine\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1a\n" +
	"\bfacility\x18\x04 \x01(\tR\bfacility\x12\x1e\n" +
	"\n" +
	"attributes\x18\x05 \x01(\fR\n" +
	"attributes\x12\x16\n" +
	"\x06labels\x18\x06 \x01(\fR\x06labels\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x12*\n" +
	"\x02ts\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x02tsB4Z2github.com/hyperscaleav/omniglass/proto/og/v1;ogv1b\x06proto3"

var (
	file_proto_og_v1_telemetry_proto_rawDescOnce sync.Once
	file_proto_og_v1_telemetry_proto_rawDescData []byte
)

func file_proto_og_v1_telemetry_proto_rawDescGZIP() []byte {
	file_proto_og_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_og_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_og_v1_telemetry_proto_rawDesc), len(file_proto_og_v1_telemetry_proto_rawDesc)))
	})
	return file_proto_og_v1_telemetry_proto_rawDescData
}

var file_proto_og_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_og_v1_telemetry_proto_goTypes = []any{
	(*TelemetryBatch)(nil),        // 0: og.v1.TelemetryBatch
	(*Owner)(nil),                 // 1: og.v1.Owner
	(*Sample)(nil),                // 2: og.v1.Sample
	(*LogLine)(nil),               // 3: og.v1.LogLine
	nil,                           // 4: og.v1.TelemetryBatch.LabelsEntry
	nil,                           // 5: og.v1.Sample.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_og_v1_telemetry_proto_depIdxs = []int32{
	6, // 0: og.v1.TelemetryBatch.ts:type_name -> google.protobuf.Timestamp
	4, // 1: og.v1.TelemetryBatch.labels:type_name -> og.v1.TelemetryBatch.LabelsEntry
	2, // 2: og.v1.TelemetryBatch.samples:type_name -> og.v1.Sample
	3, // 3: og.v1.TelemetryBatch.logs:type_name -> og.v1.LogLine
	1, // 4: og.v1.TelemetryBatch.owner:type_name -> og.v1.Owner
	6, // 5: og.v1.Sample.ts:type_name -> google.protobuf.Timestamp
	5, // 6: og.v1.Sample.labels:type_name -> og.v1.Sample.LabelsEntry
	6, // 7: og.v1.LogLine.ts:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_og_v1_telemetry_proto_init() }
func file_proto_og_v1_telemetry_proto_init() {
	if File_proto_og_v1_telemetry_proto != nil {
		return
	}
	file_proto_og_v1_telemetry_proto_msgTypes[2].OneofWrappers = []any{
		(*Sample_IntValue)(nil),
		(*Sample_DoubleValue)(nil),
		(*Sample_StringValue)(nil),
		(*Sample_JsonValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_og_v1_telemetry_proto_rawDesc), len(file_proto_og_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_og_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_og_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_og_v1_telemetry_proto_msgTypes,
	}.Build()
	File_proto_og_v1_telemetry_proto = out.File
	file_proto_og_v1_telemetry_proto_goTypes = nil
	file_proto_og_v1_telemetry_proto_depIdxs = nil
}
